name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: UI Tests
        run: make test-ui

      - name: API Tests
        run: make test-api
